package tests

import (
	"testing"
	"net/http"
	"strings"
	"encoding/json"
	"strconv"
)

func TestLoginUserChange(t *testing.T) {
	token := Login("test@localhost", "test123", t)
	if token == "" {
		t.Error("received invalid token!")
		return
	}

	// Change First Name to "new"

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	body := strings.NewReader(`{"first_name": "new"}`)
	req, err := http.NewRequest("POST", "http://localhost:3000/api/v1/user", body)
	if err != nil {
		t.Error("Failed to create req: " + err.Error())
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Error("Failed to submit req: " + err.Error())
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		t.Error("Received non-200 status: " + strconv.Itoa(resp.StatusCode))
		return
	}
	var u User
	json.NewDecoder(resp.Body).Decode(&u)
	if u.FirstName != "new" {
		t.Error("Received wrong first name: " + u.FirstName)
	}
}
